### ISSUE TITLE
Errors Generating DHCP Results

### ISSUE THREAD

**Issue by mikecay** [AsBuiltReport/AsBuiltReport.Microsoft.Windows#10]
**Describe the bug**
When executing the Microsoft Windows Report against a server running DHCP I get the following errors

`Get-DhcpServerSetting: Cannot process argument transformation on parameter 'CimSession'. Cannot convert the "CimSession: server.name" value of type "Deserialized.Microsoft.Management.Infrastructure.CimSession" to type "Microsoft.Management.Infrastructure.CimSession[]".
Get-DhcpServerDatabase: Cannot process argument transformation on parameter 'CimSession'. Cannot convert the "CimSession: server.name" value of type "Deserialized.Microsoft.Management.Infrastructure.CimSession" to type "Microsoft.Management.Infrastructure.CimSession[]".
Get-DhcpServerDnsCredential: Cannot process argument transformation on parameter 'CimSession'. Cannot convert the "CimSession: server.name" value of type "Deserialized.Microsoft.Management.Infrastructure.CimSession" to type "Microsoft.Management.Infrastructure.CimSession[]".
Get-DhcpServerv4Statistics: Cannot process argument transformation on parameter 'CimSession'. Cannot convert the "CimSession: server.name" value of type "Deserialized.Microsoft.Management.Infrastructure.CimSession" to type "Microsoft.Management.Infrastructure.CimSession[]".
Get-DhcpServerv4Scope: Cannot process argument transformation on parameter 'CimSession'. Cannot convert the "CimSession: server.name" value of type "Deserialized.Microsoft.Management.Infrastructure.CimSession" to type "Microsoft.Management.Infrastructure.CimSession[]".
Get-DhcpServerv4OptionValue: Cannot process argument transformation on parameter 'CimSession'. Cannot convert the "CimSession: server.name" value of type "Deserialized.Microsoft.Management.Infrastructure.CimSession" to type "Microsoft.Management.Infrastructure.CimSession[]".
Get-DhcpServerv4Scope: Cannot process argument transformation on parameter 'CimSession'. Cannot convert the "CimSession: server.name" value of type "Deserialized.Microsoft.Management.Infrastructure.CimSession" to type "Microsoft.Management.Infrastructure.CimSession[]".
`

The report is generated but without the DHCP details.
I am running AsBuiltReport on Windows Server 2016 and the target server, with DHCP installed, is also Windows Server 2016.

**To Reproduce**
Run the module against a Windows Server 2016 with DHCP installed

**Expected behavior**
The report to be created with the DHCP details 

**Desktop (please complete the following information):**
PowerShell 7.2.6
PowerCLI 12.7

**Comment by rebelinux** [comment]
Is the dhcp server also a Domain Controller?

**Comment by mikecay** [comment]
No it is not.  We ended up using Powershell 5.1 for all the Microsoft
AsBuiltReports.  Powershell 7.6 was throwing a bunch of errors and 5.1 if
fine.

Mike

**Comment by rebelinux** [comment]
Updated the documentation to point out the supported powershell version.
