### ISSUE TITLE
Microsoft.Windows report has a typo

### ISSUE THREAD

**Issue by walkersway** [AsBuiltReport/AsBuiltReport.Microsoft.Windows#28]
### Bug description

Section 1.2.1 of the repot is missing the t off host. 

"The following section details hos OS configuration"

Get-AbrWinOSConfig.ps1 line 30 requires correcting. 

                Paragraph 'The following section details hos OS configuration'

### Command-line input

n/a

### Steps to reproduce

n/a

### Expected behaviour

n/a

### Screenshots

n/a

### Operating System

n/a

### PowerShell Version

n/a

### PowerShell Modules

Name                            Version
----                            -------
AsBuiltReport.Core              1.4.0
AsBuiltReport.Microsoft.Windows 0.5.3
PScribo                         0.10.0

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://www.asbuiltreport.com/about/contributing/#reporting-issues-and-bugs).
- [X] I have read [the documentation](https://www.asbuiltreport.com/user-guide/new-asbuiltconfig), and referred to the [known issues](https://www.asbuiltreport.com/support/known-issues/) before submitting this bug report.
- [X] I have checked for previously opened & closed [issues](https://github.com/AsBuiltReport/AsBuiltReport.Microsoft.Windows/issues) before submitting this bug report.

**Comment by rebelinux** [comment]
Thanks!
