### ISSUE TITLE
As Built Report Does Not Capture Local Users and Groups

### ISSUE THREAD

**Issue by Mark-githb** [AsBuiltReport/AsBuiltReport.Microsoft.Windows#36]
### Bug description

When running an asbuilt report against a Windows 2022 server using version 0.5.5, the report does not capture the Local Users and Groups.  When using 0.5.1 with the same parameters, this information is captured.

### Command-line input

New-AsBuiltReport -Report Microsoft.Windows -Target 'xxxxx' -Credential $Cred -Format Word -OutputFolderPath 'C:\temp' -timestamp -filename xxxxxx

### Steps to reproduce

1. Execute the line above.

### Expected behaviour

The asbuilt report to be produced with the Local Users and Groups reported as in previous versions.

### Operating System

Using Windows 11 to execute the script against a Windows 2022 server.

### PowerShell Version

Name                           Value
----                           -----
PSVersion                      5.1.22621.4391
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.4391
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### PowerShell Modules

Name                            Version
----                            -------
AsBuiltReport.Core              1.4.0
AsBuiltReport.Microsoft.Windows 0.5.5
PScribo                         0.10.0
AsBuiltReport.Core              1.4.0
AsBuiltReport.Core              1.3.0
AsBuiltReport.Microsoft.Windows 0.5.5
AsBuiltReport.Microsoft.Windows 0.5.3
AsBuiltReport.Microsoft.Windows 0.5.2
AsBuiltReport.Microsoft.Windows 0.5.1
AsBuiltReport.Microsoft.Windows 0.4.0
PScribo                         0.10.0

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://www.asbuiltreport.com/about/contributing/#reporting-issues-and-bugs).
- [X] I have read [the documentation](https://www.asbuiltreport.com/user-guide/new-asbuiltconfig), and referred to the [known issues](https://www.asbuiltreport.com/support/known-issues/) before submitting this bug report.
- [X] I have checked for previously opened & closed [issues](https://github.com/AsBuiltReport/AsBuiltReport.Microsoft.Windows/issues) before submitting this bug report.

**Comment by rebelinux** [comment]
Could you run these cmdlet and send me the logs?

 Enable powershell debugging:

```powershell
$global:VerbosePreference = 'Continue'
$global:DebugPreference = 'Continue'
Start-Transcript -Path .\Output.log
New-AsBuiltReport   <-- change this part with your parameters-->
Stop-Transcript
```

The commands generate the Output.log file which you can send to me at:

jcolonf@zenprsolutions.com

After saving the log, reset powershell to default settings:

```powershell
$global:VerbosePreference = 'SilentlyContinue'
$global:DebugPreference = 'SilentlyContinue'
```

**Comment by Mark-githb** [comment]
Jonathan,

Please find attached the output.log file.  I see now the teminating error "ScriptContent" which I thought was corrected already.

Thank you for taking the time to check it out,


Mark

________________________________

**Comment by rebelinux** [comment]
Where is the output.log file?

**Comment by Mark-githb** [comment]
It was attached to my reply to your email.

It must have been stripped off.  I'll try an upload to GitHub instead.

Mark



________________________________

**Comment by Mark-githb** [comment]
Did the attachment come through this time?

Mark 

________________________________

**Comment by Mark-githb** [comment]
[Output.log](https://github.com/user-attachments/files/17831053/Output.log)

In case the email attachment did not make it through.  Thank you.

**Comment by rebelinux** [comment]
Please try v0.5.6 and let me know if the problem is fixed!

`Update-Module AsBuiltReport.Microsoft.Windows -Force   `

**Comment by Mark-githb** [comment]
Yes, it appears to be fixed now.

Thank you,


Mark



________________________________
