### ISSUE TITLE
Read me Path is wrong

### ISSUE THREAD

**Issue by iron-2** [AsBuiltReport/AsBuiltReport.Microsoft.Windows#9]
The path in readme under Configuration is wrong I think.
It is currently "New-AsBuiltReportConfig -Report AsBuiltReport.Microsoft.Windows -FolderPath <User specified folder> -Filename <Optional>"

But -Report should be only "Microsoft.Windows"?

Atleast I got an error until I change that line.

![image](https://user-images.githubusercontent.com/31862965/199044470-e47be166-1e5f-4792-9634-b159b06c855b.png)

//Henke

**Comment by rebelinux** [comment]
Fixed!  thank you
